name = "app"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
lustre = ">= 4.6.1 and < 5.0.0"
sketch = ">= 3.1.1 and < 4.0.0"
sketch_lustre = ">= 1.0.3 and < 2.0.0"

[dev-dependencies]
lustre_dev_tools = ">= 1.6.0 and < 2.0.0"
gleeunit = ">= 1.0.0 and < 2.0.0"
