name = "fortfoundation"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
plinth = ">= 0.5.5 and < 1.0.0"
kitten = ">= 0.0.2 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
