name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  sub_packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sub_package: ["fortfound_core", "fortfound_app"]

    defaults:
      run:
        working-directory: ${{ matrix.sub_package }}

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          gleam-version: "1"
          rebar3-version: "3"

      - name: Fetch dependencies
        run: gleam deps download

      - name: Build
        run: gleam build --warnings-as-errors

      - name: Check formatting
        run: gleam format --check

      - name: Test
        if: matrix.sub_package == 'fortfound_core'
        run: gleam test
